### ISSUE TITLE
Error when DEBUG level is enabled

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#103]
07:22:21,003 ERROR [org.mobicents.servlet.sip.core.session.SipApplicationSessionAsyncTask] (MSS-Executor-Thread-0) An unexpected exception happened in the SipApplicationSessionAsynchronousWork callback on sip application session b79e7549;RestComm: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at org.mobicents.servlet.sip.core.session.SipManagerDelegate.dumpSipSessions(SipManagerDelegate.java:468)
        at org.mobicents.servlet.sip.catalina.SipStandardManager.dumpSipSessions(SipStandardManager.java:254)
        at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1198)
        at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1009)
        at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.sendSipMessage(DlgcSipB2BUA.java:542) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcMobiSipB2BUA$DlgcMobiAsyncSipTask.run(DlgcMobiSipB2BUA.java:82) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcMobiSipB2BUA$DlgcMobiAsyncSipTask.runTask(DlgcMobiSipB2BUA.java:93) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUAWorkManager.execute(DlgcSipB2BUAWorkManager.java:86) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.scheduleTask(DlgcSipB2BUA.java:456) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerStates.sendSipMessage(DlgcXSdpPortManagerStates.java:271) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerStates.helperConnectLeg(DlgcXSdpPortManagerStates.java:414) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXCreatedState.evSdpOffer(DlgcXSdpPortManagerStates.java:924) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerFSM.evProcessSdpOffer(DlgcXSdpPortManagerFSM.java:73) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcSdpPortManager.processSdpOffer(DlgcSdpPortManager.java:191) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcSdpPortManagerProxy$3.run(DlgcSdpPortManagerProxy.java:312) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at com.vendor.dialogic.javax.media.mscontrol.asyncMgr.mobicents.DlgcAsyncWorkDispatcherMobicentsImplementor$2.doAsynchronousWork(DlgcAsyncWorkDispatcherMobicentsImplementor.java:53) [dialogic309-5.0-experimental-jboss.jar:5.0-snapshot Build 133 - Experimental]
        at org.mobicents.servlet.sip.core.session.SipApplicationSessionAsyncTask.run(SipApplicationSessionAsyncTask.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_91]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_91]

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/103/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/core/session/SipManagerDelegate.java#L468

**Comment by jaimecasero** [comment]
Apparently the impl Collection doesnt support that method

**Comment by jaimecasero** [comment]
AS wrokaround set that logger level to info
            <logger category="org.mobicents.servlet.sip.core.session.SipManagerDelegate">
                <level name="INFO"/>
            </logger>

**Comment by jaimecasero** [comment]
http://stackoverflow.com/a/25705596/118052
