### ISSUE TITLE
NPE while load testing

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#107]
12:59:29,773 ERROR [org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl] (MSS-Executor-Thread-9) Problem handling transaction termination: java.lang.NullPointerException
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl$6.run(SipApplicationDispatcherImpl.java:1563) [sip-servlets-impl-3.1.650.jar:3.1.650]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/107/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
msg itself is null!!
https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/core/SipApplicationDispatcherImpl.java#L1563

**Comment by hrosa** [comment]
These exceptions happened when load testing a Dial SIP scenario with 300 concurrent calls and 25 CPS.

This is the resulting log with ERROR threshold, after ~25k calls.
[errors-mss-restcomm.txt](https://github.com/RestComm/sip-servlets/files/105216/errors-mss-restcomm.txt)

**Comment by hrosa** [comment]
Increased the MGCP timeout interval on RestComm configuration to avoid timeout problems resulting of interop with Media Server (from 500ms to 1500ms).

Repeated tests with 300 concurrent calls and 10 CPS.

The logs no longer show exceptions from RestComm side, only a single call failed in a total of 10k calls.
Still have many NPEs from Sip Servlets.

[errors-mss-restcomm.txt](https://github.com/RestComm/sip-servlets/files/106486/errors-mss-restcomm.txt)

**Comment by jaimecasero** [comment]
[sip-servlets-impl-3.0.0-SNAPSHOT.jar.zip](https://github.com/RestComm/sip-servlets/files/106712/sip-servlets-impl-3.0.0-SNAPSHOT.jar.zip) @hrosa ,please test it whenver you can

**Comment by deruelle** [comment]
Added fix in https://github.com/RestComm/sip-servlets/commit/c128185b1fc45fb4bd41ae76320e0eddfbd1fee5 to prevent 

Caused by: java.lang.NullPointerException
	at org.mobicents.servlet.sip.message.TransactionApplicationData.cleanUpMessage(TransactionApplicationData.java:271)
	at org.mobicents.servlet.sip.message.SipServletRequestImpl.sendAck(SipServletRequestImpl.java:1796)
	at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1141)
	... 15 more
