### ISSUE TITLE
java.lang.ClassCastException in InitialRequestDispatcher

### ISSUE THREAD

**Issue by agnoix** [RestComm/sip-servlets#108]
I don't know whether it's a issue...

SIP Servlet version:
TelScale-SIP-Servlets-7.0.4.355-apache-tomcat-8.0.26
Issue discription:
1. No application router info in $CATALINA_HOME/conf/dars/mobicents-dar.properties;
2. Used command ./sipp -sn uac -sf uac.xml 120.24.103.132:5080 -m 1
    The content of the uac.xml as below, missing the "sip:" in the request uri
    <send retrans="500">
    <![CDATA[

      REGISTER [remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] 127.0.0.1:[local_port];branch=[branch]
      From: ua1 <sip:ua1@127.0.0.1:[local_port]>;tag=[call_number]
      To: ua1 <sip:ua1@127.0.0.1:[local_port]>;tag=[call_number]
      Route:<sip:SimpleApplicatio@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 REGISTER
      Contact: sip:ua1@127.0.0.1:[local_port]
      Content-Length: 0
      Expires: 300

    ]]>
  </send>

  <recv response="200" rtd="true">
  </recv>

3.  Get a Exception in  SIP Servlet and receive a BYE message.
java.lang.ClassCastException: gov.nist.javax.sip.address.GenericURI cannot be cast to javax.sip.address.SipURI
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchOutsideContainer(InitialRequestDispatcher.java:474)
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchMessage(InitialRequestDispatcher.java:304)
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processRequest(SipApplicationDispatcherImpl.java:880)
	at gov.nist.javax.sip.EventScanner.deliverRequestEvent(EventScanner.java:250)
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:146)
	at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185)
	at gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:1324)
	at gov.nist.javax.sip.stack.SIPServerTransactionImpl.processRequest(SIPServerTransactionImpl.java:811)
	at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:568)
	at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:514)
	at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:319)
	at java.lang.Thread.run(Thread.java:745)

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/108/create?referer=github" target="_blank">Log Time</a>

**Comment by deruelle** [comment]
I provided a fix for this issue, but the root issue is that your REGISTER is malformed, the Request URI should be REGISTER **sip**:[remote_ip]:[remote_port] SIP/2.0 instead of REGISTER [remote_ip]:[remote_port] SIP/2.0.
Also why don't you provide a DAR file ? the REGISTER will not be routed to the application if you don't provide one

**Comment by agnoix** [comment]
There's some misunderstanding  in my expression.
Actually I just wondered why there is  a java.lang.ClassCastException, becasue a wrong URI?
The exception throw in  line 474 of org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher
javax.sip.address.SipURI sipRequestUri = (javax.sip.address.SipURI)request.getRequestURI();

I saw the Exception when I didn't setup my ENV well.
My test app runs well in the SIP Servlet.

**Comment by deruelle** [comment]
Yes, I fixed it in https://github.com/RestComm/sip-servlets/commit/b8b8536e7425bf2f23fd26598f419c7de2d1c76b 
Thanks for reporting it !
