### ISSUE TITLE
NPE during sip container startup on wildfly 8

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/sip-servlets#116]
```
15:29:45,857 ERROR [org.jboss.ws.common.deployment] (MSC service thread 1-13) () JBWS022102: Cannot stop endpoint in state UNDEFINED: jboss.ws:context=my-sipapp-asc,endpoint=org.example.ws.MyWebService
15:29:45,873 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-13) () MSC000001: Failed to start service jboss.deployment.unit."my-sipapp-asc.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."my-sipapp-asc.war".INSTALL: JBAS018733: Failed to process phase INSTALL of deployment "my-sipapp-asc.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [wildfly-server-8.2.1.Final-SNAPSHOT.jar:8.2.1.Final-SNAPSHOT]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60]
Caused by: java.lang.NullPointerException
	at org.mobicents.servlet.sip.undertow.SipContextImpl.getApplicationName(SipContextImpl.java:520)
	at org.mobicents.servlet.sip.undertow.SipContextImpl.prepareServletContextServices(SipContextImpl.java:384)
	at org.mobicents.as8.deployment.UndertowSipDeploymentInfoService.<init>(UndertowSipDeploymentInfoService.java:62)
	at org.mobicents.as8.deployment.UndertowSipDeploymentInfoProcessor.deploy(UndertowSipDeploymentInfoProcessor.java:88)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [wildfly-server-8.2.1.Final-SNAPSHOT.jar:8.2.1.Final-SNAPSHOT]
	... 5 more
```

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/116/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
wildfly8 support is still a bit experimental. I'll try to reproduce and debug this asap. 

Thanks for reporting.

**Comment by AlerantAppNGIN** [comment]
Ok, thanks, I will also try to figure this out meantime.

**Comment by deruelle** [comment]
I think this one is not needed as we won't support AS8 only AS10 moving forward
