### ISSUE TITLE
in mss-3.1.633-apache-tomcat-8.0.26 and in mss-4.0.21-apache-tomcat-8.0.26 Invite does not get to the application's servlet

### ISSUE THREAD

**Issue by RomanDS** [RestComm/sip-servlets#117]
Hi all,
With Dialogic JSR 309 connector appropriate with java 1.8 when we ran the sample verification demo (takes an inbound call and then plays a "hello" file) the SIP container delivers that incoming call to JSR 309 Connector instead of the app. 
btw, it works in mss-3.1.633-apache-tomcat-7.0.64!!!!

Here are the logs with DEBUG. Please let me know what the issue might be and/or if you need additional info.
[issue.zip](https://github.com/RestComm/sip-servlets/files/157794/issue.zip)

Best regards,
Roman

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/117/create?referer=github" target="_blank">Log Time</a>

**Comment by deruelle** [comment]
It seems the INVITE is correctly dispatched to the application see log:
```
2016-03-03 17:20:32,214 DEBUG [org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher] (Mobicents-SIP-Servlets-UDPMessageChannelThread-0) Dispatching request INVITE sip:player@146.152.122.149:5080 SIP/2.0
Via: SIP/2.0/UDP 10.20.120.18:5060;branch=z9hG4bK.-twrCZORZ;rport=5060;received=10.20.120.18
From: <sip:toto@10.20.120.18>;tag=dSGDRy9jw
To: <sip:player@146.152.122.149>
CSeq: 20 INVITE
Call-ID: efRYtjhoUy
Max-Forwards: 70
Supported: outbound
Allow: INVITE,ACK,CANCEL,OPTIONS,BYE,REFER,NOTIFY,MESSAGE,SUBSCRIBE,INFO,UPDATE
Content-Type: application/sdp
Contact: <sip:toto@10.20.120.18>;+sip.instance="<urn:uuid:4b121412-646e-419e-92ef-ac722716ec5c>"
User-Agent: Linphone/3.8.5 (belle-sip/1.4.1)
Content-Length: 621

v=0
o=toto 978 2342 IN IP4 10.20.120.18
s=Talk
c=IN IP4 10.20.120.18
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7078 RTP/AVP 96 97 98 99 0 8 100 101 102 103
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1; stereo=0; sprop-stereo=0
a=rtpmap:97 SILK/16000
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=rtpmap:99 speex/8000/2
a=rtpmap:100 PCMA/8000/2
a=rtpmap:101 telephone-event/48000
a=rtpmap:102 telephone-event/16000
a=rtpmap:103 telephone-event/8000
m=video 9078 RTP/AVP 96 97
a=rtpmap:96 VP8/90000
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42801F
 to following App/servlet => dlgc_sample_demo/DlgcSipServlet on following sip session (dSGDRy9jw;efRYtjhoUy;6074d3bf;dlgc_sample_demo)
```

but there is a NPE from the driver ?

```
java.lang.NullPointerException
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcAbstractB2BUAReceiver.processSipRequestInvite(DlgcAbstractB2BUAReceiver.java:99)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcAbstractB2BUAReceiver.processSipRequestDoAction(DlgcAbstractB2BUAReceiver.java:75)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.processSipRequestDoAction(DlgcSipB2BUA.java:617)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA$DlgcReceiveRequestTask.run(DlgcSipB2BUA.java:601)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.processSipRequest(DlgcSipB2BUA.java:577)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipServlet.doRequest(DlgcSipServlet.java:169)
	at javax.servlet.sip.SipServlet.service(SipServlet.java:328)
	at org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher.callServlet(MessageDispatcher.java:369)
```

Can you share the application itself ? Maybe it's a parsing problem on sip.xml or annotations. I see that there is only 2 Servlets deployed

```
2016-03-03 17:20:03,939 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) checkIsManagedThread false , isManagedThread null, isContainerManaged true
2016-03-03 17:20:03,939 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) container DlgcSipServlet, class : org.mobicents.servlet.sip.catalina.SipServletImpl
2016-03-03 17:20:03,939 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) 2 SipServletListener to notify of servlet initialization
2016-03-03 17:20:03,941 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) container AsyncPlayer, class : org.mobicents.servlet.sip.catalina.SipServletImpl
2016-03-03 17:20:03,941 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) 2 SipServletListener to notify of servlet initialization

```

**Comment by RomanDS** [comment]
Hi Jean, that is a connector which is getting an invite. App does not.




Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by deruelle** [comment]
dlgc_sample_demo is the application right ?

Can you share the application itself ? Maybe it's a parsing problem on sip.xml or annotations. I see that there is only 2 Servlets deployed

```
2016-03-03 17:20:03,939 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) checkIsManagedThread false , isManagedThread null, isContainerManaged true
2016-03-03 17:20:03,939 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) container DlgcSipServlet, class : org.mobicents.servlet.sip.catalina.SipServletImpl
2016-03-03 17:20:03,939 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) 2 SipServletListener to notify of servlet initialization
2016-03-03 17:20:03,941 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) container AsyncPlayer, class : org.mobicents.servlet.sip.catalina.SipServletImpl
2016-03-03 17:20:03,941 DEBUG [org.mobicents.servlet.sip.startup.SipStandardContext] (main) 2 SipServletListener to notify of servlet initialization
```

**Comment by RomanDS** [comment]
Hi @deruelle, what is strange that in Dialogic.log (which logs application and connector) I did not see dlgc_sample_demo getting the request. 
Attached is the application war file. Would that do?


[dlgc_sample_demo.zip](https://github.com/RestComm/sip-servlets/files/158696/dlgc_sample_demo.zip)

**Comment by deruelle** [comment]
This seems to be due to https://github.com/RestComm/sip-servlets/issues/92

**Comment by deruelle** [comment]
Do you want to try to contribute a fix for it ?

**Comment by RomanDS** [comment]
How do I go about it?

**Comment by deruelle** [comment]
You can follow the guidelines of the [Open Source Playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit?usp=sharing)

**Comment by RomanDS** [comment]
Let me take a look.

Are annotations supported here so we could perhaps get away from a need for sip.xml? We tried to use annotations as we use on other J2EE platforms but does not seem to compile.

**Comment by deruelle** [comment]
Annotations should be supported. If not please report here as well and feel free to look into contributing that too :D

**Comment by RomanDS** [comment]
We have implemented annotations instead. No issue for Dialogic.

**Comment by deruelle** [comment]
Ok great. Marking as resolved then
