### ISSUE TITLE
WildFly AS10 TCK issues

### ISSUE THREAD

**Issue by deruelle** [RestComm/sip-servlets#133]
Excerpt below of one of the test cases failing, 

```
[2016-04-22 18:45:20,196] SipSessionAttributeListenerServlet:84 DEBUG - === got value of the specified key(key1)=null===
[2016-04-22 18:45:20,197] ApiTestMainServlet:52 INFO  - === forward the request to the servlet, name = Address ===
[31m18:45:20,197 ERROR [org.mobicents.servlet.sip.core.dispatchers.DispatchTask] (Mobicents-SIP-Servlets-UDPMessageChannelThread-3) Unexpected exception while processing message MESSAGE sip:JSR289_TCK@127.0.0.1:5080 SIP/2.0
Call-ID: f6c87de6d7655f7f9cd87043c4b84335@127.0.0.1
CSeq: 1 MESSAGE
From: "Alice" <sip:alice@127.0.0.1:5071>;tag=1693650031
To: "JSR289_TCK" <sip:JSR289_TCK@127.0.0.1:5080>
Via: SIP/2.0/UDP 127.0.0.1:5071;branch=z9hG4bKd35eb18980e9ffff9f2a1ae6bac1a875
Max-Forwards: 5
Route: <sip:127.0.0.1:5080;lr;transport=udp>
Method-Name: testToString001
Servlet-Name: Address
Content-Length: 0

: java.lang.NullPointerException
	at com.bea.sipservlet.tck.apps.api.ApiTestMainServlet.doRequest(ApiTestMainServlet.java:57)
	at javax.servlet.sip.SipServlet.service(SipServlet.java:328) [sip-servlets-spec-4.0.72.jar:4.0.72]
	at org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher.callServlet(MessageDispatcher.java:369) [sip-servlets-impl-4.0.72.jar:4.0.72]
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher$InitialDispatchTask.dispatch(InitialRequestDispatcher.java:748) [sip-servlets-impl-4.0.72.jar:4.0.72]
	at org.mobicents.servlet.sip.core.dispatchers.DispatchTask.dispatchAndHandleExceptions(DispatchTask.java:58) [sip-servlets-impl-4.0.72.jar:4.0.72]
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchInsideContainer(InitialRequestDispatcher.java:451) [sip-servlets-impl-4.0.72.jar:4.0.72]
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchMessage(InitialRequestDispatcher.java:306) [sip-servlets-impl-4.0.72.jar:4.0.72]
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processRequest(SipApplicationDispatcherImpl.java:861) [sip-servlets-impl-4.0.72.jar:4.0.72]
	at gov.nist.javax.sip.EventScanner.deliverRequestEvent(EventScanner.java:250) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:146) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:1324) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.stack.SIPServerTransactionImpl.processRequest(SIPServerTransactionImpl.java:811) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:578) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:524) [jain-sip-ri-1.2.281.jar:1.2.281]
	at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:319) [jain-sip-ri-1.2.281.jar:1.2.281]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

```

the line failing is actually doing this with the handler being the value of Servlet-Name header in the SIP Message above

```
 logger.info("=== forward the request to the servlet, name = " + handler + " ===");
      SipSession session = req.getSession();
      session.setHandler(handler);
      RequestDispatcher dispatcher = 
          getServletContext().getNamedDispatcher(handler);
      dispatcher.forward(req,null);
```

You can see the full log at https://mobicents.ci.cloudbees.com/job/RestcommSipServletsWildfly10TCK/ws/AS-stdout-log-jboss.txt/*view*/

**Comment by deruelle** [comment]
@AlerantAppNGIN much better after the merge. Only 4 tests left, see 
https://mobicents.ci.cloudbees.com/job/RestcommSipServletsWildfly10TCK/14/testReport/.

Let me know if you need more insights on what failed for each test

**Comment by deruelle** [comment]
@AlerantAppNGIN Great job. Clean run https://mobicents.ci.cloudbees.com/job/RestcommSipServletsWildfly10TCK/25/testReport/ !
