### ISSUE TITLE
WildFly shutdown NPE issue

### ISSUE THREAD

**Issue by deruelle** [RestComm/sip-servlets#134]
After downloading the latest Snapshot from https://mobicents.ci.cloudbees.com/job/RestcommSipServlets-4.X-Release/lastSuccessfulBuild/artifact/, when I stop and start the container I get the following Exception:

```
19:50:14,543 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-7) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
19:50:14,543 ERROR [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0043: Deployment unit processor org.mobicents.as10.deployment.UndertowSipDeploymentProcessor@c505030 unexpectedly threw an exception during undeploy phase INSTALL of deployment "media-jsr309-servlet.war": java.lang.NullPointerException
	at org.mobicents.as10.deployment.UndertowSipDeploymentProcessor.removeFromConvergedDeployments(UndertowSipDeploymentProcessor.java:178)
	at org.mobicents.as10.deployment.UndertowSipDeploymentProcessor.undeploy(UndertowSipDeploymentProcessor.java:165)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.safeUndeploy(DeploymentUnitPhaseService.java:272) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.stop(DeploymentUnitPhaseService.java:230) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StopTask.stopService(ServiceControllerImpl.java:2056) [jboss-msc-1.2.6.Final.jar:1.2.6.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StopTask.run(ServiceControllerImpl.java:2017) [jboss-msc-1.2.6.Final.jar:1.2.6.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_72-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_72-internal]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_72-internal]
```

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/134/create?referer=github" target="_blank">Log Time</a>

**Comment by deruelle** [comment]
Fixed in https://github.com/RestComm/sip-servlets/pull/135
