### ISSUE TITLE
Fix NPE ShootistSipServletRFC3263Test (6)

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#152]
NPE at test code 
java.lang.NullPointerException
	at org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootist(ShootistSipServletRFC3263Test.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

 org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootist	1 min 29 sec	84
 org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootistTLSwithTLSConnector	1 min 25 sec	84
 org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootistTLSwithTCPConnector	1 min 25 sec	84
 org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootistTCP	1 min 27 sec	84
 org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootistCancel	2 min 6 sec	84
 org.mobicents.servlet.sip.testsuite.simple.rfc3263.ShootistSipServletRFC3263Test.testShootistErrorResponse

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/152/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
Fixed by providing more details on mock. There is till a problem with testShootistErrorResponse, not sending message to all hops...
