### ISSUE TITLE
Fix FileNotFoundExceptionon Click2CallBasicTest.testClickToCallHttpSessionLeak

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#156]
Click2CallBasicTest.testClickToCallHttpSessionLeak

java.io.FileNotFoundException: http://127.0.0.1:8080/click2call/index.html
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at org.mobicents.servlet.sip.testsuite.click2call.Click2CallBasicTest.testClickToCallHttpSessionLeak(Click2CallBasicTest.java:211)

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/156/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
for some reason index.html is not available at junit environment. If i deploy the very same war into an actual environment, the html is shown in the browser.

**Comment by jaimecasero** [comment]
this is certainly a tes environment issue, changing priority
