### ISSUE TITLE
Fix NPE on SpeedDialLocationServiceStaticServerAddressTest.testSpeedDialLocationServiceCalleeSendBye

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#157]
java.lang.NullPointerException
	at org.mobicents.servlet.sip.message.SipServletMessageImpl.getSipSession(SipServletMessageImpl.java:1159)
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processTransactionTerminated(SipApplicationDispatcherImpl.java:1564)
	at gov.nist.javax.sip.EventScanner.deliverTransactionTerminatedEvent(EventScanner.java:448)
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:156)
	at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185)

**Comment by jaimecasero** [comment]
For some reason bye is denied with 481:
2016-06-22 17:24:40,852 DEBUG receiver-UDPMessageChannelThread-0 gov.nist.core.LogWriter.logDebug(LogWriter.java:216) - gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:362) [transaction state = Trying Transaction]
2016-06-22 17:24:40,852 DEBUG receiver-UDPMessageChannelThread-0 gov.nist.core.LogWriter.logDebug(LogWriter.java:216) - gov.nist.javax.sip.stack.SIPTransactionStack.getDialog(SIPTransactionStack.java:1010) [getDialog(08b789fd0f826b2c8c0677a704fb8986@127.0.0.1:5210945:1857783) : returning null]
2016-06-22 17:24:40,852 DEBUG receiver-UDPMessageChannelThread-0 gov.nist.core.LogWriter.logDebug(LogWriter.java:216) - gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:428) [dialogId = 08b789fd0f826b2c8c0677a704fb8986@127.0.0.1:5210945:1857783]
2016-06-22 17:24:40,852 DEBUG receiver-UDPMessageChannelThread-0 gov.nist.core.LogWriter.logDebug(LogWriter.java:216) - gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:429) [dialog = null]
2016-06-22 17:24:40,852 DEBUG receiver-UDPMessageChannelThread-0 gov.nist.core.LogWriter.logDebug(LogWriter.java:216) - gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:798) [dropping request -- automatic dialog support enabled and dialog does not exist!]
2016-06-22 17:24:40,852 DEBUG receiver-UDPMessageChannelThread-0 gov.nist.core.LogWriter.logDebug(LogWriter.java:216) - gov.nist.javax.sip.stack.SIPServerTransactionImpl.sendMessage(SIPServerTransactionImpl.java:913) [sipServerTransaction::sendMessage SIP/2.0 481 Call leg/Transaction does not exist
