### ISSUE TITLE
IPv6 Connector  in server.xml is throwing exception on SipSessionImpl.setOutboundInterface

### ISSUE THREAD

**Issue by eranlevi76** [RestComm/sip-servlets#167]
Hi,
I am using mss-4.0.21-apache-tomcat-8.0.26, which contains sip-servlets-impl-4.0.21.jar.
I am trying to setup an IPv6 address in the Connector in the server.xml, same as either of the below two examples below:

1)
<Connector port="5070"
        ipAddress = "2a02:ed0:1000:3031::1600"
        protocol="org.mobicents.servlet.sip.startup.SipProtocolHandler"
        signalingTransport="udp"/>

or

2)
<Connector port="5070"
        ipAddress = "**[**2a02:ed0:1000:3031::1600**]**"
        protocol="org.mobicents.servlet.sip.startup.SipProtocolHandler"
        signalingTransport="udp"/>

In both options, in the log, i see the following printout:

> 2016-06-19 12:43:45,838 DEBUG [SipNetworkInterfaceManagerImpl] (main) Outbound Interface List :
> 2016-06-19 12:43:45,838 DEBUG [SipNetworkInterfaceManagerImpl] (main) Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5070;transport=udp
> 2016-06-19 12:43:45,838 DEBUG [SipNetworkInterfaceManagerImpl] (main) Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5061;transport=tcp
> 2016-06-19 12:43:45,838 DEBUG [SipNetworkInterfaceManagerImpl] (main) Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5081;transport=tls
> 2016-06-19 12:43:45,839 DEBUG [SipNetworkInterfaceManagerImpl] (main) Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5082;transport=ws

i am trying to run the following code lines, in order to use method setOutboundInterface:

1)
`request.getSession().setOutboundInterface(new java.net.InetSocketAddress("[2a02:ed0:1000:3031:0:0:0:1600]", 5070));
`
or 

2)
`request.getSession().setOutboundInterface(new java.net.InetSocketAddress("2a02:ed0:1000:3031:0:0:0:1600", 5070));`

but both are throwing the following exception:

```
java.lang.IllegalArgumentException: Network interface for 2a02:ed0:1000:3031:0:0:0:1600:5070 not found
        at org.mobicents.servlet.sip.core.session.SipSessionImpl.setOutboundInterface(SipSessionImpl.java:1976)
        at org.mobicents.servlet.sip.message.MobicentsSipSessionFacade.setOutboundInterface(MobicentsSipSessionFacade.java:198)
        at com.ele.asnetiservices.signaling.sipengine.common.SipHelper.setIncomingOutboundInterface(SipHelper.java:603)
        at com.ele.asnetiservices.signaling.sipengine.core.machines.InitialFSM.initFromRequest(InitialFSM.java:560)
        at com.ele.asnetiservices.signaling.sipengine.core.machines.InitialFSM.init(InitialFSM.java:276)
        at com.ele.asnetiservices.signaling.sipengine.core.machines.InitialFSM.transition_11_1_guard(InitialFSM.java:836)
        at com.ele.asnetiservices.signaling.sipengine.core.machines.InitialFSM$35.invoke(InitialFSM.java:119)
        at org.echarts.TransitionTarget.evaluateGuard(TransitionTarget.java:51)
        at org.echarts.BasicTransitionTarget.satisfiesGuard(BasicTransitionTarget.java:43)
        at org.echarts.CompoundTransitionTarget.satisfiesGuard(CompoundTransitionTarget.java:38)
        at org.echarts.MachineMessagelessTransitions.getEnabledTransition(MachineMessagelessTransitions.java:108)
        at org.echarts.MachineMessagelessTransitions.getMaxEnabledTransition(MachineMessagelessTransitions.java:58)
        at org.echarts.TransitionMachine.resetMaxEnabledMessagelessTransition(TransitionMachine.java:696)
        at org.echarts.TransitionMachine.resetActiveTransitions(TransitionMachine.java:408)
        at org.echarts.TransitionMachine.resetActiveTransitions(TransitionMachine.java:286)
        at org.echarts.TransitionMachine.resetActiveTransitions(TransitionMachine.java:270)
        at org.echarts.TransitionMachine.runMessageTransitionSequence(TransitionMachine.java:1249)
        at org.echarts.TransitionMachine.run(TransitionMachine.java:1122)
        at org.echarts.servlet.sip.FeatureBox.advanceBoxMachine(FeatureBox.java:279)
        at org.echarts.servlet.sip.BoxPort.input(BoxPort.java:44)
        at org.echarts.servlet.sip.EChartsSipServlet.dispatchToFreeBox(EChartsSipServlet.java:552)
        at org.echarts.servlet.sip.EChartsSipServlet.doRequest(EChartsSipServlet.java:490)
        at com.ele.asnetiservices.signaling.sipengine.core.SipEngineServlet.doRequest(SipEngineServlet.java:398)
        at javax.servlet.sip.SipServlet.service(SipServlet.java:328)
        at org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher.callServlet(MessageDispatcher.java:369)
        at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher$InitialDispatchTask.dispatch(InitialRequestDispatcher.java:746)
        at org.mobicents.servlet.sip.core.dispatchers.DispatchTask.dispatchAndHandleExceptions(DispatchTask.java:58)
        at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchInsideContainer(InitialRequestDispatcher.java:451)
        at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchMessage(InitialRequestDispatcher.java:306)
        at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processRequest(SipApplicationDispatcherImpl.java:841)
        at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:230)
        at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185)
        at gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:1324)
        at gov.nist.javax.sip.stack.SIPServerTransactionImpl.processRequest(SIPServerTransactionImpl.java:807)
        at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:560)
        at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:512)
        at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:317)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jaimecasero** [comment]
could you send the list of ips/adapters in your system (ifconfig -a)?

**Comment by eranlevi76** [comment]
[root@rhel-65-31-52 ~]# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:50:56:A5:3B:65
          inet addr:172.20.31.54  Bcast:172.20.31.255  Mask:255.255.255.0
          inet6 addr: 2a02:ed0:1000:3031:250:56ff:fea5:3b65/64 Scope:Global
          inet6 addr: fe80::250:56ff:fea5:3b65/64 Scope:Link
          inet6 addr: 2a02:ed0:1000:3031::1600/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2120351 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1800679 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1369708497 (1.2 GiB)  TX bytes:1006201614 (959.5 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:288520441 errors:0 dropped:0 overruns:0 frame:0
          TX packets:288520441 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:26626204892 (24.7 GiB)  TX bytes:26626204892 (24.7 GiB)

**Comment by jaimecasero** [comment]
Hi,
During server bootstrap, the list of network interfaces identifed will be printed on log file. Could you enable debug level for sipServlet logger, and attach the resulting server.log file?

The error you mentioned happens when this list doesnt contain the IP address...

we need to look for traces with text "Outbound Interface : ".

thanks in advance, regards

**Comment by eranlevi76** [comment]
Hi, i have pasted it before on the original post.
i am attaching it again now below.

2016-06-19 12:43:45,838 DEBUG SipNetworkInterfaceManagerImpl Outbound Interface List :
2016-06-19 12:43:45,838 DEBUG SipNetworkInterfaceManagerImpl Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5070;transport=udp
2016-06-19 12:43:45,838 DEBUG SipNetworkInterfaceManagerImpl Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5061;transport=tcp
2016-06-19 12:43:45,838 DEBUG SipNetworkInterfaceManagerImpl Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5081;transport=tls
2016-06-19 12:43:45,839 DEBUG SipNetworkInterfaceManagerImpl Outbound Interface : sip:[2a02:ed0:1000:3031:0:0:0:1600]:5082;transport=ws

**Comment by eranlevi76** [comment]
Hi Jaime, 
i have done some changes in the java class SipNetworkInterfaceManagerImpl, then i have built the jar again and than i was able to use IPv6.
I am attaching the file here, as txt file, as i cannot attach java files here.
you can see my changes where my name is in the remarks in the code.
thanks
eran



[SipNetworkInterfaceManagerImpl.txt](https://github.com/RestComm/sip-servlets/files/329257/SipNetworkInterfaceManagerImpl.txt)
