### ISSUE TITLE
NPE on session cleanup

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#194]
14:17:10,346 ERROR [org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl] (MSS-Executor-Thread-1) Problem handling transaction termination: java.lang.NullPointerException
    at org.mobicents.servlet.sip.core.session.SipSessionImpl.removeOngoingTransaction(SipSessionImpl.java:1591) [sip-servlets-impl-7.0.4.452.jar:7.0.4.452]
    at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl$7.run(SipApplicationDispatcherImpl.java:1687) [sip-servlets-impl-7.0.4.452.jar:7.0.4.452]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]

probably cuased by concurrent access..

**Comment by maria-farooq** [comment]
@jaimecasero here are complete logs https://app.box.com/s/0zwceuroclhv8d2kyf6iucrcm0cuf216

**Comment by maria-farooq** [comment]
https://telestax.slack.com/archives/logentries-rc-core/p1478170997000051
