### ISSUE TITLE
Create/Add EAP7 release script

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#208]
<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/208/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
runnign server we get this:
13:04:25,285 ERROR [stderr] (Thread-73) Exception in thread "Thread-73" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
13:04:25,290 ERROR [stderr] (Thread-73)         at com.telscale.licensing.notify.NotifierImpl.<init>(NotifierImpl.java:17)
13:04:25,290 ERROR [stderr] (Thread-73)         at com.telscale.licensing.LicenseEnforcerImpl.<init>(LicenseEnforcerImpl.java:15)
13:04:25,290 ERROR [stderr] (Thread-73)         at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl$3.run(SipApplicationDispatcherImpl.java:536)
13:04:25,290 ERROR [stderr] (Thread-73)         at java.lang.Thread.run(Thread.java:745)
13:04:25,291 ERROR [stderr] (Thread-73) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException from [Module "org.mobicents.libs:main" from local module loader @42f30e0a (finder: local module finder @24273305 (roots: /root/TelScale-SIP-Servlets-8.0.0.16-jboss-eap-7.0/modules,/root/TelScale-SIP-Servlets-8.0.0.16-jboss-eap-7.0/modules/system/layers/base))]
13:04:25,302 ERROR [stderr] (Thread-73)         at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
13:04:25,302 ERROR [stderr] (Thread-73)         at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
13:04:25,302 ERROR [stderr] (Thread-73)         at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
13:04:25,303 ERROR [stderr] (Thread-73)         at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
13:04:25,303 ERROR [stderr] (Thread-73)         ... 4 more

**Comment by jaimecasero** [comment]
fixed adding proper module dependency
