### ISSUE TITLE
Troubleshoot Wildfly10 TCK/TestSuite issues

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#212]
<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/212/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
encodeUrl002:the servlet is returning thsi encodedURL:
13:34:44,833  INFO ConvergedHttpSessionServlet:99 - === testEncodeURL002() ===
13:34:44,835 DEBUG ConvergedHttpSessionServlet:63 - the baseURL=http://127.0.0.1:8180/apitestapp/ConvergedHttpSession
13:34:44,835 DEBUG ConvergedHttpSessionServlet:64 - the encodedURL=http://localhost:8080/apitestapp/foo.jsp;jsessionid=bqEBj-OwZmSqCVzLXAmdexFXv9J37_BT0_ZmYvYk
13:34:47,862  INFO ConvergedHttpSessionServlet:99 - === testGetApplicationSession001() ===

but the server is listening on 8180, not 8080, so subsequent request form test fails with connection failure

**Comment by jaimecasero** [comment]
the server output is full of
[0m[31m15:04:58,987 ERROR [org.mobicents.servlet.sip.core.dispatchers.DispatchTask] (Restcomm-SIP-Servlets-UDPMessageChannelThread-15) Unexpected exception while processing message MESSAGE sip:JSR289_TCK@127.0.0.1:5180 SIP/2.0
Call-ID: 86c16e6dd714a0f4f2991fd8d099cc7b@10.237.47.204
CSeq: 1 MESSAGE
From: "Alice" <sip:alice@10.237.47.204:5071>;tag=928919459
To: "JSR289_TCK" <sip:JSR289_TCK@127.0.0.1:5180>
Via: SIP/2.0/UDP 10.237.47.204:5071;branch=z9hG4bK595ad39b2acad66ccafc1caba9b9f999
Max-Forwards: 5
Route: <sip:127.0.0.1:5180;lr;transport=udp>
Method-Name: testSessionDestroyed001
Servlet-Name: SipApplicationSessionListener
Content-Length: 0

: java.lang.NoClassDefFoundError: com/bea/sipservlet/tck/utils/TestUtil
	at com.bea.sipservlet.tck.apps.BaseServlet.doRequest(BaseServlet.java:50)
	at javax.servlet.sip.SipServlet.service(SipServlet.java:328) [sip-servlets-spec-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.session.SipRequestDispatcher.forward(SipRequestDispatcher.java:60) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at com.bea.sipservlet.tck.apps.api.ApiTestMainServlet.doRequest(ApiTestMainServlet.java:57)
	at javax.servlet.sip.SipServlet.service(SipServlet.java:328) [sip-servlets-spec-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher.callServlet(MessageDispatcher.java:386) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher$InitialDispatchTask.dispatch(InitialRequestDispatcher.java:839) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.dispatchers.DispatchTask.dispatchAndHandleExceptions(DispatchTask.java:61) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchInsideContainer(InitialRequestDispatcher.java:509) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.dispatchers.InitialRequestDispatcher.dispatchMessage(InitialRequestDispatcher.java:333) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processRequest(SipApplicationDispatcherImpl.java:955) [sip-servlets-impl-8.0.0.13.jar:8.0.0.13]
	at gov.nist.javax.sip.EventScanner.deliverRequestEvent(EventScanner.java:250) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:146) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:1328) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.stack.SIPServerTransactionImpl.processRequest(SIPServerTransactionImpl.java:851) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:581) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:527) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:325) [jain-sip-ri-7.0.5.287.jar:7.0.5.287]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_121]

apparently the class is compiled and foudn in proper directory...

**Comment by jaimecasero** [comment]
testSessionDestroyed001 use to be a false positive

**Comment by jaimecasero** [comment]
these are failing testsuite not present in SS7 branch
 org.mobicents.servlet.sip.testsuite.b2bua.B2BUASipUnitTest.testB2BUASipUnit	14 sec	1
 org.mobicents.servlet.sip.testsuite.b2bua.B2BUASipUnitTest.testB2BUASipUnitCancelNoResponse	2.3 sec	1
 org.mobicents.servlet.sip.testsuite.b2bua.forking.B2BUASipServletForkingTest.testB2BUAForkingWithCANCEL	48 sec	1
 org.mobicents.servlet.sip.testsuite.callcontroller.CallBlockingTest.testCallBlockingInvite	1.1 sec	1
 org.mobicents.servlet.sip.testsuite.callcontroller.CallControllerSipUnitTest.testCallBlockingBothDeployed	38 ms	1
 org.mobicents.servlet.sip.testsuite.callcontroller.CallControllerSipUnitTest.testCallBlockingInvite	2.2 sec	1
 org.mobicents.servlet.sip.testsuite.concurrency.CongestionControlTest.testMemoryCongestedErrorResponseReInvite	44 sec	1
 org.mobicents.servlet.sip.testsuite.deployment.GracefulStopTest.testServiceGracefulShutdownNegativeValue	4.4 sec	1
 org.mobicents.servlet.sip.testsuite.deployment.GracefulStopTest.testServiceGracefulShutdownNegativeValueJMX	4.3 sec	1
 org.mobicents.servlet.sip.testsuite.routing.ExternalRoutingServletTest.testExternalRouting	14 sec	1

**Comment by jaimecasero** [comment]
latest run didnt bring any failure on wildfly10
http://ci.telestax.com/view/SS8/job/TelScale-SIP-Servlets-8-Wildfly-10-TCK/lastCompletedBuild/testReport/

**Comment by jaimecasero** [comment]
![image](https://cloud.githubusercontent.com/assets/7847241/23303258/4919935c-fa93-11e6-8f28-0b73ec3953a9.png)
testMemoryCongestedErrorResponseR works locally

**Comment by jaimecasero** [comment]
![image](https://cloud.githubusercontent.com/assets/7847241/23303325/b842b916-fa93-11e6-994b-5011fd0dc2df.png)
testB2BUAForkingWithCANCEL works locally
