### ISSUE TITLE
Sip-servlet on java 8 cannot start If configure LB: path-name="org.mobicents.ha.balancing.only"

### ISSUE THREAD

**Issue by xhoaluu** [RestComm/sip-servlets#351]
When set up:

<subsystem xmlns="urn:org.mobicents:sip-servlets-as10:1.0" application-router="configuration/dars/mobicents-dar.properties" stack-properties="configuration/mss-sip-stack.properties" path-name="org.mobicents.ha.balancing.only" app-dispatcher-class="org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl" concurrency-control-mode="SipApplicationSession">
            <connector name="sip-udp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-udp" use-load-balancer="true" load-balancer-address="192.168.1.2" load-balancer-rmi-port="2000"  load-balancer-sip-port="5065"/>
            <connector name="sip-tcp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tcp" use-load-balancer="true" load-balancer-address="192.168.1.2" load-balancer-rmi-port="2000"  load-balancer-sip-port="5065"/>
            <connector name="sip-tls" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tls"/>
            <connector name="sip-ws" protocol="SIP/2.0" scheme="sip" socket-binding="sip-ws"/>
            <connector name="sip-wss" protocol="SIP/2.0" scheme="sip" socket-binding="sip-wss"/>
        </subsystem>

2017-12-14 10:48:35,971 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.sip: org.jboss.msc.service.StartException in service jboss.sip: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.6.Final.jar:1.2.6.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_111]
Caused by: java.lang.ExceptionInInitializerError
        at org.mobicents.as10.SipServerService.start(SipServerService.java:277)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.6.Final.jar:1.2.6.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.6.Final.jar:1.2.6.Final]
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Invalid bundle interface org.mobicents.as10.SipMessages (implementation not found)
        at org.jboss.logging.Messages$1.run(Messages.java:83)
        at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_111]
        at org.jboss.logging.Messages.getBundle(Messages.java:58)
        at org.jboss.logging.Messages.getBundle(Messages.java:46)
        at org.mobicents.as10.SipMessages.<clinit>(SipMessages.java:41)
        ... 6 more

**Comment by xhoaluu** [comment]
https://telestax.atlassian.net/browse/RES-2

**Comment by nachkar** [comment]
Any news regarding this issue ?

**Comment by xhoaluu** [comment]
Hi @nachkar 
In mss-sip-stack.properties
Remve org.mobicents.ha.javax.sip.CACHE_CLASS_NAME=org.mobicents.ha.javax.sip.cache.infinispan.InfinispanCache

**Comment by nachkar** [comment]
Hi @xhoaluu 

My mss-sip-stack.properties file doesnt contain org.mobicents.ha.javax.sip.CACHE_CLASS_NAME=org.mobicents.ha.javax.sip.cache.infinispan.InfinispanCache

**Comment by xhoaluu** [comment]
Can you upload your mss-sip-stack.properties

**Comment by nachkar** [comment]
gov.nist.javax.sip.LOG_MESSAGE_CONTENT=true
gov.nist.javax.sip.LOG4J_LOGGER_NAME=gov.nist
gov.nist.javax.sip.TRACE_LEVEL=LOG4J
gov.nist.javax.sip.DEBUG_LOG=logs/mss-jsip-debuglog.txt
gov.nist.javax.sip.SERVER_LOG=logs/mss-jsip-messages.xml
javax.sip.STACK_NAME=Mobicents-SIP-Servlets
javax.sip.AUTOMATIC_DIALOG_SUPPORT=off
gov.nist.javax.sip.DELIVER_UNSOLICITED_NOTIFY=true
gov.nist.javax.sip.THREAD_POOL_SIZE=64
gov.nist.javax.sip.REENTRANT_LISTENER=true
# prevent DOS attacks
gov.nist.javax.sip.MAX_LISTENER_RESPONSE_TIME=120
gov.nist.javax.sip.MAX_MESSAGE_SIZE=10000
# setting up the buffer size to reduce retransmissions and avoid loosing messages
gov.nist.javax.sip.RECEIVE_UDP_BUFFER_SIZE=65536
gov.nist.javax.sip.SEND_UDP_BUFFER_SIZE=65536
gov.nist.javax.sip.AGGRESSIVE_CLEANUP=true
gov.nist.javax.sip.MAX_FORK_TIME_SECONDS=0
# set to true so that the stack do more validation on dialog, 
# but won't work on chained applications so false by default
gov.nist.javax.sip.AUTOMATIC_DIALOG_ERROR_HANDLING=false
gov.nist.javax.sip.MESSAGE_PROCESSOR_FACTORY=gov.nist.javax.sip.stack.NioMessageProcessorFactory
org.mobicents.servlet.sip.USER_AGENT_HEADER=Mobicents Sip Servlets 3.0.0-SNAPSHOT
org.mobicents.servlet.sip.SERVER_HEADER=Mobicents Sip Servlets 3.0.0-SNAPSHOT
gov.nist.javax.sip.PATCH_SIP_WEBSOCKETS_HEADERS=true

#Sip load balancer configuration
org.mobicents.ha.javax.sip.BALANCERS=BALANCERS=192.168.153.212:5065
gov.nist.javax.sip.PATCH_SIP_WEBSOCKETS_HEADERS=true
org.mobicents.ha.javax.sip.LoadBalancerHeartBeatingServiceClassName=org.mobicents.ha.javax.sip.MultiNetworkLoadBalancerHeartBeatingServiceImpl
org.mobicents.ha.javax.sip.LOCAL_HTTP_PORT=8080
org.mobicents.ha.javax.sip.LOCAL_SSL_PORT=8443
gov.nist.javax.sip.TCP_POST_PARSING_THREAD_POOL_SIZE=16
gov.nist.javax.sip.LINGER_TIMER=0
gov.nist.javax.sip.CONGESTION_CONTROL_TIMEOUT=0
gov.nist.javax.sip.RELEASE_REFERENCES_STRATEGY=Aggressive
org.mobicents.ha.javax.sip.REACHABLE_CHECK=false

**Comment by ocarriles** [comment]
Same issue occurs with default path-name
 
<subsystem xmlns="urn:jboss:domain:weld:3.0"/>
        <subsystem xmlns="urn:org.mobicents:sip-servlets-as10:1.0" application-router="configuration/dars/mobicents-dar.properties" stack-properties="configuration/mss-sip-stack.properties" path-name="org.mobicents.ext" app-dispatcher-class="org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl" concurrency-control-mode="SipApplicationSession">
            <connector name="sip-udp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-udp"/>
            <connector name="sip-tcp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tcp"/>
            <connector name="sip-tls" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tls"/>
            <connector name="sip-ws" protocol="SIP/2.0" scheme="sip" socket-binding="sip-ws"/>
            <connector name="sip-wss" protocol="SIP/2.0" scheme="sip" socket-binding="sip-wss"/></subsystem>

**Comment by ocarriles** [comment]
<subsystem xmlns="urn:jboss:domain:weld:3.0"/>
        <subsystem xmlns="urn:org.mobicents:sip-servlets-as10:1.0" application-router="configuration/dars/mobicents-dar.properties" stack-properties="configuration/mss-sip-stack.properties" path-name="org.mobicents.ext" app-dispatcher-class="org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl" concurrency-control-mode="SipApplicationSession">
            <connector name="sip-udp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-udp"/>
            <connector name="sip-tcp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tcp"/>
            <connector name="sip-tls" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tls"/>
            <connector name="sip-ws" protocol="SIP/2.0" scheme="sip" socket-binding="sip-ws"/>
            <connector name="sip-wss" protocol="SIP/2.0" scheme="sip" socket-binding="sip-wss"/></subsystem>

**Comment by ocarriles** [comment]
double chequed inconsistency in my mss-sip-stack.properties.
rolling back to default config solves the issue for me.

**Comment by islamoglus** [comment]
@ocarriles Can you share your successful configuration ?
