### ISSUE TITLE
Getting exception while starting the Apache Tomcat 4.0-8

### ISSUE THREAD

**Issue by arnab-naha** [RestComm/sip-servlets#92]
We are getting an exception while starting the Tomcat 4.0-8 version of the mobicent. I am not able to attach our simple demo project zip but I am attaching the sip.xml as sip.xml.txt and the server log file.
[sip.xml.txt](https://github.com/Mobicents/sip-servlets/files/57133/sip.xml.txt)
.

09-Dec-2015 09:45:26.874 SEVERE [localhost-startStop-1] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception
 java.lang.IllegalAccessException: Class org.apache.tomcat.util.digester.ObjectCreateRule can not access a member of class org.mobicents.servlet.sip.catalina.PatternRule with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
	at org.mobicents.servlet.sip.catalina.PatternRule.begin(SipRuleSet.java:638)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1178)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1363)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1470)
	at org.mobicents.servlet.sip.startup.SipContextConfig.configureStart(SipContextConfig.java:176)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
	at org.mobicents.servlet.sip.startup.SipContextConfig.lifecycleEvent(SipContextConfig.java:90)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5066)
	at org.mobicents.servlet.sip.startup.SipStandardContext.startInternal(SipStandardContext.java:437)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.mobicents.servlet.sip.catalina.SipHostConfig.deployWAR(SipHostConfig.java:163)
	at org.mobicents.servlet.sip.catalina.SipHostConfig.deploySAR(SipHostConfig.java:151)
	at org.mobicents.servlet.sip.catalina.SipHostConfig$DeploySar.run(SipHostConfig.java:402)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[servlet-examples.2015-12-09.txt](https://github.com/Mobicents/sip-servlets/files/57126/servlet-examples.2015-12-09.txt)

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/92/create?referer=github" target="_blank">Log Time</a>

**Comment by deruelle** [comment]
Confirmed. It seems Tomcat 8 changed the way of parsing hence https://github.com/Mobicents/sip-servlets/blob/master/containers/sip-servlets-catalina-8/src/main/java/org/mobicents/servlet/sip/catalina/SipRuleSet.java#L627 is failing. Want to try contributing a fix ?

**Comment by jaimecasero** [comment]
For tomcat7 PatternRule was extending NodeCreateRule. This rule has been discontinued in tomcat8 code, but we can migrate the old code and reuse.

I found there was a problem with parsing in Tomcat7 as well        digester.addSetNext(prefix + "sip-app/servlet",
                            "addChild"
                            ,"org.apache.catalina.Container");

the third parameter was commented for some reason
